### ISSUE TITLE
Thermal Expansion Crashes Randomy

### ISSUE THREAD

**Issue by Ristellise** [Joshwoo70/feedback#9]
## Issue description:
On launch, The game randomly crashes.

## What happens:
Crash

## What you expected to happen:
Not Crashing

## Reproduction Steps:
1. Launch Game....
2. Wait.... ???
3. Profit or crash!

#### Version (make sure you are on the latest version before reporting):

- Forge: 1.10.2-12.18.3.2297
- Pack Version: Pre-Alpha

Does this issue occur on a server? 
- N/A

#### Crashlog:

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. 
During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals())
but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().
See bullet point two in that method's documentation.
object #1 =class cofh.thermalexpansion.util.managers.machine.PulverizerManager$ComparableItemStackPulverizer id= 1638993249 hashCode= 684 toString= cofh.thermalexpansion.util.managers.machine.PulverizerManager$ComparableItemStackPulverizer@1638993249{m:0, i:net.minecraft.item.ItemBlock@2114443384, v:7168};
object #2 =class cofh.thermalexpansion.util.managers.machine.PulverizerManager$ComparableItemStackPulverizer id= 863887786 hashCode= 469762048 toString= cofh.thermalexpansion.util.managers.machine.PulverizerManager$ComparableItemStackPulverizer@863887786{m:0, i:net.minecraft.item.ItemBlock@2114443384, v:7168}
```
[Gist](https://gist.github.com/Joshwoo70/c81e2de79592ba389c1552dace4d17a6)

**Comment by Ristellise** [comment]
Probably FoamFix causing those issues. we will see when we updates...

**Comment by asiekierka** [comment]
Not on other people's classes, and this doesn't look like my class. I examined the code, and I think it's caused by this:

https://github.com/CoFH/CoFHLib/blob/1.10.2/src/main/java/cofh/lib/util/ComparableItem.java#L64-L67

The item ID can change any time you swap worlds, or connect to a different server - which would change the hashCode. I suppose using the hashCode() of the Item itself would be more appropriate. Or the registry name String's.

>Whenever it is invoked on the same object more than once during an execution of a Java application, the hashCode method must consistently return the same integer, provided no information used in equals comparisons on the object is modified.

**Comment by asiekierka** [comment]
@KingLemming

**Comment by asiekierka** [comment]
Of course, after changing the registry IDs, the items would still be equal. Either way, I don't touch ItemStack, Item, OreDictionary or any related hashCode in any way which could influence this.

@Joshwoo70 You could try disabling model deduplication, as well as options pertaining to faster Property objects.

**Comment by KingLemming** [comment]
This happens when mods register their oredictionary things too late. Initialize should be the absolute latest for this stuff, but some people screw it up.

**Comment by Ristellise** [comment]
seems to happen obly occationally but not all them time...

**Comment by KingLemming** [comment]
Yeah - basically we'll see this when a mod is doing oredict reg in postinit, and the mod load order is randomized.

Point is, they're doing it too late. The reason that the hashcode is the OreID is because it allows for implicit oredict capability - ANY item w/ that OreID results in the correct recipe.

**Comment by Ristellise** [comment]
ah thanks for the info :)

**Comment by Ristellise** [comment]
untill i can find this darn mod ill leave it open...
